name: either_option_example
version: 1.0.0
author: cb yannick <cbyannick@gmail.com>
homepage: https://github.com/cbyad/either_option
repository: https://github.com/cbyad/either_option
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  either_option:
    path: ../

